---
apiVersion: autoscaling/v2beta1
kind: HorizontalPodAutoscaler
metadata:
  name: api
  namespace: numbers
spec:
  minReplicas: 2
  maxReplicas: 2
  scaleTargetRef:
    apiVersion: extensions/v1beta1
    kind: Deployment
    name: api
  metrics:
    - type: Resource
      resource:
        name: memory
        targetAverageUtilization: 80
---
apiVersion: v1
kind: Service
metadata:
  namespace: numbers
  name: api-service
  labels:
    app: api
spec:
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3000
  selector:
    app: api
  type: ClusterIP
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  namespace: numbers
  name: api
spec:
  replicas: 1
  template:
    metadata:
      labels: # labels to select/identify the deployment
        app: api
    spec: # pod spec
      containers:
        - name: numbers-api
          image: gcr.io/assemble-services/numbers-server:latest
          ports:
            - containerPort: 3000
          resources:
            requests:
              memory: "500Mi"
              cpu: "500m"
            limits:
              memory: "1Gi"
              cpu: "1"
          env:
            - name: MODE
              value: "SERVER"
            - name: TELNYX_API_USER
              valueFrom:
                secretKeyRef:
                  name: main-secrets
                  key: telnyxApiUser
            - name: TELNYX_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: main-secrets
                  key: telnyxApiToken
            - name: TELNYX_AUTH_TOKEN
              valueFrom:
                secretKeyRef:
                  name: main-secrets
                  key: telnyxAuthToken
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: main-secrets
                  key: databaseUrl
            - name: APPLICATION_SECRET
              valueFrom:
                secretKeyRef:
                  name: main-secrets
                  key: applicationSecret
            - name: ADMIN_ACCESS_TOKEN
              valueFrom:
                secretKeyRef:
                  name: main-secrets
                  key: adminAccessSecret
            - name: BASE_URL
              value: "https://numbers.assemble.live"

            # Datadog
            - name: DD_AGENT_HOST
              valueFrom:
                fieldRef:
                  fieldPath: status.hostIP
            - name: DD_DOGSTATSD_PORT
              valueFrom:
                secretKeyRef:
                  name: main-secrets
                  key: ddDogstatsdPort
