apiVersion: v1
kind: ConfigMap
metadata:
  name: pg-rewired-config
  namespace: numbers
data:
  user.conf: |-
    max_connections=200

    # Logs
    log_line_prefix= '%m [%p] %d %a %u %h %c '
    # logging_collector = on
    # log_statement = 'all'
