apiVersion: kubedb.com/v1alpha1
kind: Postgres
metadata:
  name: postgres
  namespace: numbers
spec:
  version: "11.2"
  replicas: 1
  # standbyMode: Hot
  nodeSelector:
    cloud.google.com/gke-nodepool: bigger-pool
  # Storage
  storageType: Durable
  storage:
    storageClassName: "ssd"
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 50Gi
  # Backups
  backupSchedule:
    cronExpression: '@every 1h'
    gcs:
      bucket: backups.assemble.live
      prefix: db_numbers
    storageSecretName: gcs-secret
  # Custom Postgres user.conf
  configSource:
    configMap:
      name: pg-rewired-config
  # DB Pods Template
  podTemplate:
    metadata:
      annotations:
        ad.datadoghq.com/postgres.check_names: '["postgres"]'
        ad.datadoghq.com/postgres.init_configs: "[{}]"
        ad.datadoghq.com/postgres.instances: |-
          [{
            "host": "%%host%%",
            "port": "%%port%%",
            "username": "datadog",
            "password": "%%env_DATADOG_PASSWORD%%",
            "collect_activity_metrics": "true",
            "collect_function_metrics": "true",
            "tags": ["db-cluster:numbers"]
          }]
        ad.datadoghq.com/postgres.logs: |-
          [{
            "source":"postgresql",
            "service":"postgresql",
            "tags": ["db-cluster:numbers"],
            "log_processing_rules": [
              {
                "type": "multi_line",
                "pattern": "\d{4}\-(0?[1-9]|1[012])\-(0?[1-9]|[12][0-9]|3[01])",
                "name": "new_log_start_with_date"
              }
            ]
          }]
    spec:
      env:
        - name: DATADOG_PASSWORD
          valueFrom:
            secretKeyRef:
              name: main-secrets
              key: ddPostgresPassword
      resources:
        requests:
          memory: "25Gi"
          cpu: "12"
        limits:
          memory: "25Gi"
          cpu: "12"
  terminationPolicy: DoNotTerminate
