# Note: invalid YAML file – copy to deploy/secrets and fill in the values
# before running kubectl create or kubectl apply
apiVersion: v1
kind: Secret
metadata:
  namespace: numbers
  name: main-secrets
type: Opaque
stringData:
  telnyxApiUser:
  telnyxApiToken:
  telnyxAuthToken:
  databaseUrl:
  applicationSecret:
  adminAccessSecret:

  # Datadog
  ddDogstatsdPort: '8125'
  ddPostgresPassword: 'SomethingSecret'
